default: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  default_host: <%= ENV['DEFAULT_HOST'] %>
  aws:
    key: <%= ENV['AWS_KEY'] %>
    secret: <%= ENV['AWS_SECRET'] %>
    bucket: <%= ENV['AWS_BUCKET'] %>
    region: <%= ENV['AWS_REGION'] %>

development:
  <<: *default
  secret_key_base: f9e39d16671f05ac0d6a36e23119994b7e8b834fda9f5181d3118f0a7465f1792d8b743179a0f9fd6b112f903b9f57c6fc30a1fa534804eb5f1586d504c7bbef

test:
  <<: *default
  secret_key_base: 367ab85649ebf2de9751275f3e1ad99fe974d0785c29582244e392cf1c3dbd63153baf9dced749ced10214dba9760bd1fb02758927acbe68f8005f0f44a0ceae
  aws:
    key: test
    secret: test
    bucket: test
    region: test

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  explain: <%= ENV["EXPLAIN_QUERY"] %>
